/** Build a freenet-git first-commit shell script from in-browser create/upload. */

export interface CommitFile {
  path: string;
  content: string;
}

function shellSingleQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function heredocBody(content: string): string {
  // Prefer literal heredoc; if content contains the delimiter, fall back to printf.
  if (!content.includes("GATLAS_EOF")) {
    return content;
  }
  return content.replace(/\r\n/g, "\n");
}

function toBase64Utf8(s: string): string {
  const bytes = new TextEncoder().encode(s);
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}

export function buildFirstCommitScript(input: {
  remote: string;
  branch: string;
  label: string;
  subject: string;
  description?: string;
  files: CommitFile[];
}): string {
  const branch = input.branch || "main";
  const lines: string[] = [
    "#!/usr/bin/env bash",
    "# Generated by GitAtlas — run on a machine with git-remote-freenet + owner identity.",
    "set -euo pipefail",
    `DIR=${shellSingleQuote(input.label)}`,
    'mkdir -p "$DIR"',
    'cd "$DIR"',
    `git init -b ${shellSingleQuote(branch)}`,
  ];

  for (const file of input.files) {
    const path = file.path.replace(/^\/+/, "");
    const dir = path.includes("/") ? path.slice(0, path.lastIndexOf("/")) : "";
    if (dir) {
      lines.push(`mkdir -p ${shellSingleQuote(dir)}`);
    }
    if (file.content.includes("GATLAS_EOF")) {
      const b64 = toBase64Utf8(file.content);
      lines.push(
        `printf '%s' ${shellSingleQuote(b64)} | base64 -d > ${shellSingleQuote(path)}`,
      );
    } else {
      lines.push(
        `cat > ${shellSingleQuote(path)} <<'GATLAS_EOF'`,
        heredocBody(file.content).replace(/\r\n/g, "\n").replace(/\n$/, ""),
        "GATLAS_EOF",
      );
      if (file.content.length && !file.content.endsWith("\n")) {
        lines.push(`printf '\\n' >> ${shellSingleQuote(path)}`);
      }
    }
  }

  lines.push("git add -A");
  const msg = input.description?.trim()
    ? `${input.subject.trim()}\n\n${input.description.trim()}`
    : input.subject.trim();
  lines.push(`git commit -m ${shellSingleQuote(msg)}`);
  lines.push(`git remote add origin ${shellSingleQuote(input.remote)}`);
  lines.push(`git push -u origin ${shellSingleQuote(branch)}`);
  lines.push("");
  return lines.join("\n");
}

export function downloadTextFile(filename: string, text: string): void {
  const blob = new Blob([text], { type: "text/x-shellscript" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.rel = "noopener";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
