/**
 * Generated-file detection — path rules from go-enry + common content checks.
 */
import generatedNames from "./generated/generated-names.json";
import { compileLinguistRegex } from "./ruby-regex";

interface GeneratedNamesFile {
  extensions: string[];
  name_rules: { kind: "regex" | "contains" | "endsWith"; pattern: string }[];
}

const data = generatedNames as GeneratedNamesFile;
const extSet = new Set(data.extensions.map((e) => e.toLowerCase()));
const nameRules = data.name_rules.map((r) => {
  if (r.kind === "regex") {
    const re = compileLinguistRegex(r.pattern);
    if (!re) return () => false;
    return (path: string) => re.test(path);
  }
  if (r.kind === "contains") {
    return (path: string) => path.includes(r.pattern);
  }
  return (path: string) => path.endsWith(r.pattern);
});

function extOf(path: string): string {
  const base = path.replace(/\\/g, "/").split("/").pop() ?? "";
  const i = base.lastIndexOf(".");
  return i > 0 ? base.slice(i).toLowerCase() : "";
}

function decode(content: string | Uint8Array): string {
  return typeof content === "string"
    ? content
    : new TextDecoder("utf-8", { fatal: false }).decode(content);
}

/** Minified / generated-by-content heuristics (Linguist-inspired). */
function contentLooksGenerated(
  path: string,
  content: string | Uint8Array,
): boolean {
  const text = decode(content);
  const ext = extOf(path);
  if (ext === ".map" && text.trimStart().startsWith('{"version":')) return true;
  if (/\.min\.(js|css)$/i.test(path) || ext === ".js" || ext === ".css") {
    const lines = text.split(/\r?\n/);
    if (ext === ".js" || ext === ".css") {
      if (lines.some((l) => l.length > 5000)) return true;
    } else if (lines.some((l) => l.length > 110)) {
      return true;
    }
  }
  const head = text.slice(0, 4096);
  if (/^\/\*[!*]?\s*Generated by\b/m.test(head)) return true;
  if (/^\/\/\s*Generated by\b/m.test(head)) return true;
  if (head.includes("@generated")) return true;
  return false;
}

export function isGenerated(
  path: string,
  content?: string | Uint8Array | null,
): boolean {
  const norm = path.replace(/\\/g, "/");
  const ext = extOf(norm);
  if (extSet.has(ext)) return true;
  if (nameRules.some((fn) => fn(norm))) return true;
  if (content != null && contentLooksGenerated(norm, content)) return true;
  return false;
}
