/* AUTO-GENERATED by scripts/gen-contract-hashes.mjs — do not edit by hand */
/* repo: /var/mnt/windows_stripe/Projects/Freenet/freenet-git/crates/freenet-git/contracts/repo-contract.wasm */
/* pack: /var/mnt/windows_stripe/Projects/Freenet/freenet-git/crates/freenet-git/contracts/pack-contract.wasm */

/** BLAKE3 of freenet-git repo-contract.wasm (base58, 32 bytes decoded). */
export const REPO_WASM_HASH_B58 = "C1bhzU2LbdyNt8jBAZNpcqqPeQvpcWU3hkYUQ1ZfZnNW";

/** BLAKE3 of freenet-git pack-contract.wasm (base58, 32 bytes decoded). */
export const PACK_WASM_HASH_B58 = "5Piu7V1PjjcPVnTvUbyMdDiyvwoBprBPZ4GFUHfabyzW";

/** Hex forms (debug / tests). */
export const REPO_WASM_HASH_HEX = "a397cc99e79f99e2d320a24b0d4db5f6ab36d1f35e8454c87bf996e249ad9c13";
export const PACK_WASM_HASH_HEX = "4140e677d7715f74805d958a47c52ec13b174dcda77ccfb6fa30204f257a0a87";
