/* AUTO-GENERATED by scripts/gen-forge-owner-constants.mjs — do not edit by hand */
/* registry: /mnt/windows_stripe/Projects/Freenet/freenet-gitforge/target/wasm32-unknown-unknown/release/freenet_forge_registry.wasm */
/* identity wasm: /mnt/windows_stripe/Projects/Freenet/freenet-gitforge/target/wasm32-unknown-unknown/release/freenet_forge_identity.wasm */
/* vault wasm: /mnt/windows_stripe/Projects/Freenet/freenet-gitforge/target/wasm32-unknown-unknown/release/freenet_forge_vault.wasm */
/* stars wasm: /mnt/windows_stripe/Projects/Freenet/freenet-gitforge/target/wasm32-unknown-unknown/release/freenet_forge_stars.wasm */
/* profile wasm: /mnt/windows_stripe/Projects/Freenet/freenet-gitforge/target/wasm32-unknown-unknown/release/freenet_forge_profile.wasm */
/* repo wasm: /mnt/windows_stripe/Projects/Freenet/freenet-gitforge/target/wasm32-unknown-unknown/release/freenet_forge_repo.wasm */
/* identity code hash source: fdev inspect (packaged) */

/** UTF-8 parameters for the singleton ForgeRegistry instance. */
export const FORGE_REGISTRY_PARAMS_UTF8 = "gitforge-registry-v1";

/** BLAKE3 of hub_registry.wasm (base58). */
export const FORGE_REGISTRY_WASM_HASH_B58 = "CpgwaNDPXX3KXQ1hXFXVC8HkgfvpuMPR5MqeuEVgDCtt";

/** UTF-8 parameters prefix for GitForge vault (vault_id hex appended by SPA). */
export const FORGE_VAULT_PARAMS_PREFIX = "gitforge-vault-v1:";

/** BLAKE3 of hub_vault.wasm (base58). Empty until vault artefact is passed. */
export const FORGE_VAULT_WASM_HASH_B58 = "ERFnzsRgSnUwJF6U3Dzs7LiVowQtzyUd2r5mGcNuFmhQ";

/** UTF-8 parameters for the singleton GitForge stars instance. */
export const FORGE_STARS_PARAMS_UTF8 = "gitforge-stars-v1";

/** BLAKE3 of hub_stars.wasm (base58). Empty until stars artefact is passed. */
export const FORGE_STARS_WASM_HASH_B58 = "2C84yT51WMVpfNQXoUbqAN7DR2rKnvcdUGHvSrMX3YSZ";

/** UTF-8 parameters prefix for GitForge profile (fingerprint appended by SPA). */
export const FORGE_PROFILE_PARAMS_PREFIX = "gitforge-profile-v1:";

/** BLAKE3 of hub_profile.wasm (base58). Empty until profile artefact is passed. */
export const FORGE_PROFILE_WASM_HASH_B58 = "3jGgkdpe5fB9LuNZeuhMKTGgEBCrtKvMcBDQsboWXkgh";

/** UTF-8 parameters prefix for ForgeRepoMeta (repo_prefix appended by SPA). */
export const FORGE_REPO_PARAMS_PREFIX = "gitforge-repo-v1:";

/** BLAKE3 of hub_repo.wasm (base58). Empty until repo-meta artefact is passed. */
export const FORGE_REPO_WASM_HASH_B58 = "95bcgEE1SK9z7zvL4JcwPR2GmCbgYFtQRuEoLGRvZrj6";

/** Identity delegate key = blake3(code_hash) as byte array (32). */
export const FORGE_IDENTITY_KEY_BYTES: number[] = [108,84,23,3,93,103,56,65,159,69,73,114,109,104,165,2,206,109,131,192,147,88,88,28,8,147,64,39,13,17,22,195];

/** Identity delegate code hash as byte array (32). */
export const FORGE_IDENTITY_CODE_HASH_BYTES: number[] = [216,27,226,73,126,71,250,126,12,161,60,67,202,180,60,209,124,80,137,255,15,56,168,7,156,95,116,217,231,44,146,146];

export function forgeOwnerContractsReady(): boolean {
  return (
    FORGE_REGISTRY_WASM_HASH_B58.length > 0 &&
    FORGE_IDENTITY_KEY_BYTES.length === 32 &&
    FORGE_IDENTITY_CODE_HASH_BYTES.length === 32
  );
}

export function forgeVaultReady(): boolean {
  return FORGE_VAULT_WASM_HASH_B58.length > 0;
}

export function forgeStarsReady(): boolean {
  return FORGE_STARS_WASM_HASH_B58.length > 0;
}

export function forgeProfileReady(): boolean {
  return FORGE_PROFILE_WASM_HASH_B58.length > 0;
}

export function forgeRepoReady(): boolean {
  return FORGE_REPO_WASM_HASH_B58.length > 0;
}
