/* AUTO-GENERATED by scripts/gen-hub-owner-constants.mjs — do not edit by hand */
/* registry: /var/mnt/windows_stripe/Projects/Freenet/freenet-hub/target/wasm32-unknown-unknown/release/freenet_hub_registry.wasm */
/* identity wasm: /var/mnt/windows_stripe/Projects/Freenet/freenet-hub/target/wasm32-unknown-unknown/release/freenet_hub_identity.wasm */
/* vault wasm: /var/mnt/windows_stripe/Projects/Freenet/freenet-hub/target/wasm32-unknown-unknown/release/freenet_hub_vault.wasm */
/* stars wasm: /var/mnt/windows_stripe/Projects/Freenet/freenet-hub/target/wasm32-unknown-unknown/release/freenet_hub_stars.wasm */
/* profile wasm: /var/mnt/windows_stripe/Projects/Freenet/freenet-hub/target/wasm32-unknown-unknown/release/freenet_hub_profile.wasm */
/* repo wasm: /var/mnt/windows_stripe/Projects/Freenet/freenet-hub/target/wasm32-unknown-unknown/release/freenet_hub_repo.wasm */
/* identity code hash source: fdev inspect (packaged) */

/** UTF-8 parameters for the singleton HubRegistry instance. */
export const HUB_REGISTRY_PARAMS_UTF8 = "gitatlas-registry-v1";

/** BLAKE3 of hub-registry.wasm (base58). */
export const HUB_REGISTRY_WASM_HASH_B58 = "GUfoAoDhJeMay8oPkKN6m63qpyLKMQQohBREMeYXR2Ca";

/** UTF-8 parameters prefix for GitAtlas vault (vault_id hex appended by SPA). */
export const HUB_VAULT_PARAMS_PREFIX = "gitatlas-vault-v1:";

/** BLAKE3 of hub-vault.wasm (base58). Empty until vault artefact is passed. */
export const HUB_VAULT_WASM_HASH_B58 = "3CFRAN8GCfAFTpofjU3VNV7ergKSfwYTH2g8Vj5F8BXe";

/** UTF-8 parameters for the singleton GitAtlas stars instance. */
export const HUB_STARS_PARAMS_UTF8 = "gitatlas-stars-v1";

/** BLAKE3 of hub-stars.wasm (base58). Empty until stars artefact is passed. */
export const HUB_STARS_WASM_HASH_B58 = "GNFR4JMF9Bpe5v3n7BjtePmLnGBAf8mpTvtVJtvYtcir";

/** UTF-8 parameters prefix for GitAtlas profile (fingerprint appended by SPA). */
export const HUB_PROFILE_PARAMS_PREFIX = "gitatlas-profile-v1:";

/** BLAKE3 of hub-profile.wasm (base58). Empty until profile artefact is passed. */
export const HUB_PROFILE_WASM_HASH_B58 = "9q9tmH7iQ6Q5DxJXq8BaG5JHoFdhmPvQWw8otaKneT9h";

/** UTF-8 parameters prefix for HubRepoMeta (repo_prefix appended by SPA). */
export const HUB_REPO_PARAMS_PREFIX = "gitatlas-repo-v1:";

/** BLAKE3 of hub-repo.wasm (base58). Empty until repo-meta artefact is passed. */
export const HUB_REPO_WASM_HASH_B58 = "BXLsZqad2vAxGMRscdSqYxNRWuaPM5aNSrJNisoTcwDF";

/** Identity delegate key = blake3(code_hash) as byte array (32). */
export const HUB_IDENTITY_KEY_BYTES: number[] = [5,104,143,218,179,89,180,238,75,148,101,255,90,124,39,238,57,200,3,32,23,177,223,205,100,207,175,143,231,60,89,127];

/** Identity delegate code hash as byte array (32). */
export const HUB_IDENTITY_CODE_HASH_BYTES: number[] = [31,183,218,15,82,244,154,125,249,68,124,130,47,247,214,253,116,226,159,93,143,232,174,69,92,235,87,209,88,75,72,124];

export function hubOwnerContractsReady(): boolean {
  return (
    HUB_REGISTRY_WASM_HASH_B58.length > 0 &&
    HUB_IDENTITY_KEY_BYTES.length === 32 &&
    HUB_IDENTITY_CODE_HASH_BYTES.length === 32
  );
}

export function hubVaultReady(): boolean {
  return HUB_VAULT_WASM_HASH_B58.length > 0;
}

export function hubStarsReady(): boolean {
  return HUB_STARS_WASM_HASH_B58.length > 0;
}

export function hubProfileReady(): boolean {
  return HUB_PROFILE_WASM_HASH_B58.length > 0;
}

export function hubRepoReady(): boolean {
  return HUB_REPO_WASM_HASH_B58.length > 0;
}
