/* AUTO-GENERATED by scripts/gen-hub-owner-constants.mjs — do not edit by hand */
/* pages wasm: /var/mnt/windows_stripe/Projects/Freenet/freenet-hub/target/wasm32-unknown-unknown/release/freenet_hub_pages.wasm */
/* pages code hash source: fdev inspect (packaged) */

/** Pages delegate key = blake3(code_hash) as byte array (32). Empty until built. */
export const HUB_PAGES_KEY_BYTES: number[] = [39,40,32,145,199,207,104,91,7,1,252,173,216,161,13,19,90,147,86,234,17,253,58,102,222,182,195,71,69,166,167,153];

/** Pages delegate code hash as byte array (32). Empty until built. */
export const HUB_PAGES_CODE_HASH_BYTES: number[] = [168,36,203,2,55,36,219,22,209,246,107,76,159,105,234,15,204,105,60,251,27,192,200,253,13,200,16,28,106,205,165,156];

export function hubPagesReady(): boolean {
  return (
    HUB_PAGES_KEY_BYTES.length === 32 &&
    HUB_PAGES_CODE_HASH_BYTES.length === 32
  );
}
