/* AUTO-GENERATED by scripts/gen-forge-owner-constants.mjs — do not edit by hand */
/* pages wasm: /mnt/windows_stripe/Projects/Freenet/freenet-gitforge/target/wasm32-unknown-unknown/release/freenet_forge_pages.wasm */
/* pages code hash source: fdev inspect (packaged) */

/** Pages delegate key = blake3(code_hash) as byte array (32). Empty until built. */
export const FORGE_PAGES_KEY_BYTES: number[] = [60,9,231,224,225,99,175,134,141,155,246,123,49,49,1,125,225,249,187,34,149,217,157,35,91,35,175,251,56,77,135,251];

/** Pages delegate code hash as byte array (32). Empty until built. */
export const FORGE_PAGES_CODE_HASH_BYTES: number[] = [47,129,7,115,250,123,163,234,62,83,194,122,92,57,2,197,174,0,24,50,178,231,120,151,138,75,82,19,183,192,171,220];

export function forgePagesReady(): boolean {
  return (
    FORGE_PAGES_KEY_BYTES.length === 32 &&
    FORGE_PAGES_CODE_HASH_BYTES.length === 32
  );
}
